version: "3.8"
services:
  surreal:
    container_name: surrealdb
    ports:
      - 8002:8000
    volumes:
      - ./data:/data
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root file:/data/kartik.db
