// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Measure { identifier: string, title: string, description: string, progress: number, effort: number, }