// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankOrdering } from "./RankOrdering";

export interface Ranking { metrics: Array<string>, controls: Array<string>, created_by: string, created_at: string, ordering: RankOrdering, identifier: string, name: string, }