// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RankOrdering } from './RankOrdering';

export interface Ranking {
	enablers: Array<string>;
	controls: Array<string>;
	created_by: string;
	created_at: string;
	ordering: RankOrdering;
	minimum_coverage: number;
	identifier: string;
	name: string;
}
