// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Tag { identifier: string, name: string, color_hex: string, created_at: string, }